### ISSUE TITLE
Configuration files location

### ISSUE THREAD

**Issue by iburrows** [jfrog/jfrog-vscode-extension#326]
Hi,
I am using Windows and WSL.
Where are the configuration files located? I am seeing **Refresh: user is not signed in** messages in the jfrog output. I am never asked how to put in my login details. It is cached somewhere but I cannot find it. I have uninstalled the extension and even deleted the jfrog cli and cleared all jfrog config in wsl and on the windows host. 

I have turned on debug mode. The first line says **Trying to read credentials from KeyStore**. Which keystore? It then resolves the platform, xray and artifactory url and then I get the not signed in log message. 

How can I fix this?
Thank you for the help.

**Comment by attiasas** [comment]
Hi @iburrows,
Please use the latest version of the vscode. from [v2.1.0](https://github.com/jfrog/jfrog-vscode-extension/releases/tag/2.1.0) we added an option to choose your connection method. (if you already logged you can disconnect first)
you can follow the instructions in the [documentations](https://github.com/jfrog/jfrog-vscode-extension/blob/master/README.md#connecting-vs-code-to-your-jfrog-environment)

Let us know if the issue persist or we can close this

**Comment by iburrows** [comment]
I am using v2.3.0 and I am unable to remove the previous credentials. I have uninstalled and installed the new version.
Where are the credentials cached?
Refresh, change ci mode are all greyed out
![image](https://user-images.githubusercontent.com/21207059/236415332-7b205d0e-276e-4c0a-bf92-d5a0ccef0ba3.png)

**Comment by iburrows** [comment]
what keystore is the extension referring to?
```
[DEBUG - 10:53:00 AM] Trying to read credentials from KeyStore...
[DEBUG - 10:53:00 AM] Resolved JFrog platform URL: https://<url>
[DEBUG - 10:53:00 AM] Resolved Xray URL: https://<url>/xray
[DEBUG - 10:53:00 AM] Resolved Artifactory URL: https://<url>/artifactory
[INFO - 10:53:01 AM] Refresh: user is not signed in
```
I have also set the env variables
* JFROG_IDE_URL
* JFROG_IDE_USERNAME
* JFROG_IDE_PASSWORD

**Comment by attiasas** [comment]
Provided by the vscode global state, this is the OS keystore, i.e stored in the filesystem by vscode.
We save the last connection so in the next login you don't need to type your it.
In order to remove the current information all you need to do is disconnect from the extension.
<img width="164" alt="image" src="https://github.com/jfrog/jfrog-vscode-extension/assets/49212512/fb81c72a-b072-4c2a-a2cf-39d9ea9ff713">
If you have issue with disabled buttons and you want to see all the actions and preform them in different way you can press:
`cmd + shift + p`, type 'Jfrog' and choose the action you want (Switch to local, disconnect, connect....)

![image](https://github.com/jfrog/jfrog-vscode-extension/assets/49212512/c48a971c-65c1-4f5b-ac09-1e72f61156eb)

From what I can see you are probably not connected, try to use the Connect action from the above and let me know if resolved

**Comment by iburrows** [comment]
Thanks that worked.
